import {path, base64Encode, assertStrictEquals} from "std";
import * as encodeUtil from "../encodeUtil.js";

const FILES_DIR = path.join(path.dirname(path.fromFileUrl(import.meta.url)), "files");

Deno.test("decode", async () =>
{
	const fileData = await Deno.readFile(path.join(FILES_DIR, "BEASLEYS.DEN"));
	const encodedData = await encodeUtil.decode(fileData, "CP437");
	assertStrictEquals(base64Encode(encodedData), "DQpUaGlzIEZpbGUgQnJvdWdodCB0byB5b3UgYnkgLi4uLi4uLi4uDQoNCg0KICAgIOKWgOKWgOKWgOKWgOKWgOKWgCAg4paA4paA4paA4paA4paA4paA4paAICDiloDiloDiloDiloDiloAgICDiloDiloDiloDiloDiloAgIOKWgOKWgCAgICAgIOKWgOKWgOKWgOKWgOKWgOKWgOKWgCDiloDiloAgICAg4paA4paAIOKWiOKWiCAg4paA4paA4paA4paA4paADQogICAg4paA4paAICAg4paA4paAIOKWgOKWgCAgICAgIOKWgOKWgCAgIOKWgOKWgCDiloDiloAgICAgICDiloDiloAgICAgICDiloDiloAgICAgICAg4paA4paAICDiloDiloAgICDiloAg4paA4paADQogICAg4paA4paA4paA4paA4paA4paAICDiloDiloDiloDiloDiloAgICDiloDiloDiloDiloDiloDiloDiloAgIOKWgOKWgOKWgOKWgOKWgCAg4paA4paAICAgICAg4paA4paA4paA4paA4paAICAgICDiloDiloDiloDiloAgICAgICAg4paA4paA4paA4paA4paADQogICAg4paA4paAICAg4paA4paAIOKWgOKWgCAgICAgIOKWgOKWgCAgIOKWgOKWgCAgICAgIOKWgOKWgCDiloDiloAgICAgICDiloDiloAgICAgICAgICDiloDiloAgICAgICAgICAgICDiloDiloANCiAgICDiloDiloDiloDiloDiloDiloAgIOKWgOKWgOKWgOKWgOKWgOKWgOKWgCDiloDiloAgICDiloDiloAg4paA4paA4paA4paA4paA4paAICDiloDiloDiloDiloDiloDiloDiloAg4paA4paA4paA4paA4paA4paA4paAICAgIOKWgOKWgCAgICAgICDiloDiloDiloDiloDiloDiloANCg0KICAgICAgICAgICAgICAgICAgICAgIOKWgOKWgOKWgOKWgOKWgOKWgCAgIOKWgOKWgOKWgOKWgOKWgOKWgOKWgCDiloDiloDiloAgICDiloDiloANCiAgICAgICAgICAgICAgICAgICAgICDiloDiloAgICDiloDiloAgIOKWgOKWgCAgICAgIOKWgOKWgOKWgOKWgCAg4paA4paADQogICAgICAgICAgICAgICAgICAgICAg4paA4paAICAg4paA4paA4paAIOKWgOKWgOKWgOKWgOKWgCAgIOKWgOKWgCDiloDiloAg4paA4paADQogICAgICAgICAgICAgICAgICAgICAg4paA4paAICAg4paA4paAICDiloDiloAgICAgICDiloDiloAgIOKWgOKWgOKWgOKWgA0KICAgICAgICAgICAgICAgICAgICAgIOKWgOKWgOKWgOKWgOKWgOKWgCAgIOKWgOKWgOKWgOKWgOKWgOKWgOKWgCDiloDiloAgICDiloDiloDiloANCg0KICAgICAgICAgICAgICAgICAgICAgICAgICAoIDQxNiApIDk0OS0xNTg3DQogICAgICAgICBBbGwgZmlsZXMgc2Nhbm5lZCB3aXRoIHRoZSBsYXRlc3QgdmVyc2lvbiBvZiBNY0FmZWUncyBzY2FuDQogICAgICAgICAgICAgICAgICAgICAgICAgICBOTyBGSUxFIFJBVElPUw0KDQo=");	// eslint-disable-line max-len
});
